config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :products, only: [:index] do 
  	resources :orders, only: :create
  end 

  resources :orders, only: [:index, :destroy] do 
  	collection do
  		delete 'empty_cart'
  	end
  end

  resources :billings, only: [] do
    collection do 
      get 'pre_pay'
      get 'execute'
    end
  end

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders 
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders 
    has_many :users , through: :orders  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders 
  has_many :products, through: :orders 
  has_many :billings 

  def cart
  	orders.where(payed: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
	def pre_pay
		#Consultar carro de compra.
	    orders = current_user.cart

	    #Cálculo del total.
	    @total = orders.pluck("price * quantity").sum()

	    #Generando array de hashes con los productos.
	    @items = orders.map do |order|
	      item = {}
	      item[:name] = order.product.name
	      item[:sku] = order.id.to_s
	      item[:price] = order.price.to_s
	      item[:currency] = 'USD'
	      item[:quantity] = order.quantity
	      item
	    end

	    @payment = PayPal::SDK::REST::Payment.new(
	      {
	        :intent =>  "sale",
	        :payer =>  {
	          :payment_method =>  "paypal" },
	        :redirect_urls => {
	          :return_url => "http://localhost:3000/billings/execute",
	          :cancel_url => "http://localhost:3000/" },
	        :transactions =>  [{
	          :item_list => {
	            :items => @items},
	          :amount =>  {
	            :total =>  @total.to_s,
	            :currency =>  "USD" },
	          :description =>  "This is the payment transaction description." }]}
	    )

	    if @payment.create
	      #Redirige a PayPal
	      redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
          redirect_to redirect_url
	    else
	      @payment.error
	    end
	end

	def execute
		@paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])

	    if @paypal_payment.execute(payer_id: params[:PayerID])

	      amount = @paypal_payment.transactions.first.amount.total

	      billing = Billing.create(
	        user: current_user,
	        code: @paypal_payment.id,
	        payment_method: 'paypal',
	        amount: amount,
	        currency: 'USD'
	      )

	      orders = current_user.cart
	      orders.update_all(payed: true, billing_id: billing.id)

	      redirect_to root_path, notice: "La compra se realizó con éxito!"
	    else
	       render plain: ":("
	    end
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_cart, only: [:index, :empty_cart]

	def empty_cart
		@cart.destroy_all
		redirect_to orders_path, notice: 'Se ha vaciado el carro'
	end
	
	def index
		@orders = current_user.cart
		@total = @orders.inject(0) {|total,order| total += order.product.price * order.quantity}
	end

	def create

		@previous_order = Order.find_by(user_id: current_user.id, product_id: params[:product_id], payed: false)

		if @previous_order.present?
			new_quantity = @previous_order.quantity + 1
			@previous_order.update(quantity: new_quantity)
			redirect_to root_path, notice: "#{@previous_order.product.name} ha sido agregado al carro."
		else

			@order = Order.new()
			@product = Product.find(params[:product_id])
			@order.product = @product
			@order.user = current_user
			@order.price = @product.price 
			if @order.save 
				redirect_to root_path, notice: "El producto ha sido agregado al carro."
			else
				redirect_to root_path, alert: "El producto NO ha sido agregado al carrito"
			end
		end
	end

	def destroy
		@order = Order.find(params[:id])

		if @order.quantity == 1
			if @order.destroy
				redirect_to orders_path, notice: 'Carro Actualizado'
			else
				redirect_to orders_path, alert: 'Error al actualizar el carro'
			end
		elsif @order.quantity > 1
			@order.quantity -= 1
			if @order.save
				redirect_to orders_path, notice: 'Carro Actualizado'
			else
				redirect_to orders_path, alert: 'Error al actualizar el carro'
			end
		end
	end

	private 

	def set_cart
		@cart = current_user.cart
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarroDeCompra</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/navbar' %>
    <% if notice.present? %>
        <div class="alert alert-success" role="alert">
          <p class="notice"><%= notice %></p>
        </div>
    <% elsif alert.present?%>
      <div class="alert alert-danger" role="alert">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div class="container">
       <%= yield %>
    </div>
   <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  </body>
</html>

app/views/orders/index.html.erb
<br><br>

<%= link_to 'Continuar comprando', root_path, class:"btn btn-warning" %> <br><br>
<%= link_to 'Vaciar Carrito', empty_cart_orders_path, class:"btn btn-warning", method: :delete%> <br><br>
<% if @orders.present? %>
	<table class="table table-hover">
		<tr>
			<th>Producto</th>
			<th>Valor Unitario</th>
			<th>Cantidad</th>
			<th>Subtotal</th>
			<th>Accion</th>
		</tr>
		<% @orders.each do |order| %>
		<tr>
			<td><%= order.product.name %></td>
			<td>$<%= order.product.price %></td>
			<td><%= order.quantity %></td>
			<td><%= order.quantity * order.product.price%></td>
			<td><%=link_to order_path(order), class: "btn btn-outline-danger btn-sm", method: :delete do %>
					<i class="fas fa-trash-alt"></i>
			<% end  %>
			</td>
		</tr>
		<% end %>

		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th>
				Total: $<%= @total %> 
			</th>
			<th></th>
		</tr>
	</table>
	<div class="row">
		<div class="col-md-2 offset-md-10">
			<%= link_to "Confirmar Compra", pre_pay_billings_path, class: 'btn btn-outline-success' %>
		</div>
	</div>
<% else %>
	<p>No tienes productos en el carrito...</p>
<% end %>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<% @products.each do |product| %>
			<div class="col-md-4 mb-3">
				<div class="card">
		  			<img class="card-img-top" src="<%= product.photo %>" alt="Card image cap">
			  		<div class="card-body text-center">
			    		<h5 class="card-title"><%= product.name %></h5>
			    		<p class="card-text">Precio: $<%= product.price %></p>
			    		<%= link_to product_orders_path(product), class: "btn btn-primary", method: :post do %> 
							<i class="fas fa-cart-plus"></i>
			    		<% end %>
			  		</div>
		  		</div>
		  	</div>
		<% end %> 
	</div>
</div>




	

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Carrito</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Mi carrito', orders_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.email, "#", class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>